"""Mem0-backed replacement for ``LocalMemoryStore``: raw fact storage really
goes through ``mem0.Memory`` now (real dependency, real embedding+vector
search), matching the paper's claim that entity nodes point to "underlying
Mem0 backend raw memory entry indices." voicemem's own cognitive_graph/
rightbrain graph layers are unchanged -- they just reference the memory_id
values mem0 hands back, instead of ids generated by ``format_memory_id()``.

Two deliberate divergences from a naive "just call mem0" integration,
verified against the actually-installed ``mem0ai`` (real source read, not
assumed from docs):

1. ``add(infer=True)`` is NOT used, and voicemem's own ADD/UPDATE/DELETE/NONE
   conflict resolver (``extract_facts_openai.ConflictResolver``) is kept as
   the decision-maker, not retired. Read ``mem0/memory/main.py``'s
   ``_add_to_vector_store`` directly: in this installed version, the
   ``infer=True`` path only does exact hash-based dedup against existing
   memories -- every extracted fact that isn't a byte-identical duplicate
   comes back with ``event: "ADD"``, there is no real semantic UPDATE/DELETE
   branch in this code path. That's weaker than what voicemem already had
   (an LLM decides ADD vs UPDATE vs DELETE vs NONE per fact, aligned with
   mem0's own official prompt). So this store uses ``add(infer=False)``,
   which just stores exactly the text it's given -- voicemem's own extractor
   and conflict resolver still do the actual decision-making upstream, mem0
   is purely "store this fact, give me back an id and a real embedding."

2. ``add_records_with_ids()`` IGNORES the caller-supplied ids. mem0's public
   ``add()`` has no id= parameter -- it always mints its own UUID. The one
   caller of this method (``LeftBrainMemoryRepository.append_extracted``)
   already treats this method's *return value* as the authoritative id list
   (zips it against ``annotated_facts`` for cognitive-graph linking), so this
   is safe: callers just start seeing mem0's ids instead of voicemem's own
   ``format_memory_id()`` ids. This is the actual mechanism by which "the
   graph layer now references mem0 ids" happens.

The lexical/time-question reranking bonus (``_lexical_time_bonus`` et al.,
tuned against real accuracy runs) is NOT something mem0 provides -- it's
re-applied here on top of whatever candidates mem0's own cosine search
returns, so migrating storage backends doesn't quietly regress that tuning.

Concurrency note (real regression found + fixed): the old ``LocalMemoryStore``
was hand-rolled SQLite in WAL mode, which natively supports many concurrent
readers. mem0's local/embedded Qdrant mode does NOT -- a second
``mem0.Memory`` client pointed at the same on-disk path raises "Storage
folder ... is already accessed by another instance of Qdrant client" the
moment it's constructed, and it's not a transient error: every subsequent
call on the FIRST client also starts failing. Real repro: a 16-worker
``ThreadPoolExecutor`` QA eval that constructs a fresh ``VoiceMem`` per
question (same ``memory_root``, common pattern -- e.g. this exact codebase's
own ``research/eval_locomo_baseline_voicemem.py``) failed 137/152 questions
this way, not occasionally -- essentially every question after the first
thread grabbed the lock. Fixed by caching one ``Memory`` client per resolved
``memory_root`` path (``_MEM0_CLIENT_CACHE`` below) -- this makes concurrent
``VoiceMem`` construction against the same path safe *within one process*
(all threads share the one real connection). It does NOT make it safe
*across processes* -- two separate Python processes pointed at the same
memory_root will still collide, because Qdrant's local mode fundamentally
has no multi-process story (its own error message says so: "use Qdrant
server instead"). Real deployments that need multi-process access to the
same memory_root need an actual Qdrant server, not local/embedded mode --
out of scope for this fix, called out here so it isn't rediscovered the
expensive way again.
"""

from __future__ import annotations

import os
import threading
from pathlib import Path
from typing import Any, Sequence

# mem0 每次操作会同步打 posthog 遥测（feature-flags 网络往返）。实测：这让每次
# Search 的向量检索步 rank_ms 从 ~8ms 暴涨到 ~280ms（占了整个 Search 的 97%）。
# 默认关掉——想开的用户自行设 MEM0_TELEMETRY=1 覆盖。必须早于任何 mem0 import
# （mem0 的 Memory 在下面方法里才 import，所以模块顶部这行一定在它之前）。
os.environ.setdefault("MEM0_TELEMETRY", "False")

from voicemem.leftbrain.local_memory_store import (
    MemorySearchHit,
    TextEmbedder,
    _DATE_Q_RE,
    _DATE_RE,
    _DURATION_Q_RE,
    _DURATION_RE,
    _content_words,
    _lexical_time_bonus,
    date_overlap_bonus,
    query_dates,
)


def _resolve_chat_model() -> str:
    return (os.environ.get("OPENAI_MODEL") or "").strip() or "gpt-4o-mini"


class _Mem0EmbedderAdapter:
    """Wraps any ``TextEmbedder`` as a real ``mem0.embeddings.base.EmbeddingBase``
    so ``mem0.Memory`` actually uses it, instead of always building its own
    internal OpenAI embedder regardless of what's passed to this store's
    constructor (previously the ``embedder`` argument was read only for
    ``.model_name``/``.dimensions`` -- see this file's git history / the
    comment that used to sit where this class now does).

    Not wired in through mem0's config-driven ``EmbedderFactory`` (its
    ``provider="langchain"`` option always calls the wrapped model's
    ``embed_query``, even when mem0 itself is embedding text to *store* --
    confirmed by reading ``mem0/embeddings/langchain.py``, not assumed).
    Instead, ``Memory.__init__`` builds a throwaway placeholder embedder from
    ``config.embedder`` and stores it on the plain public attribute
    ``self.embedding_model`` -- swapping that attribute right after
    construction (see below) is the real, correct hook: ``Memory.add()``/
    ``.search()`` call ``self.embedding_model.embed(text, "add"|"search")``
    directly, with the actual action, letting this adapter route add vs.
    search to different text (E5-family local models need a "query: "/
    "passage: " prefix distinction to hit their real accuracy -- see
    local_embedder.py in openai_voice_demo for the concrete case). An
    embedder opts into that by exposing ``embed_query_text(text) ->
    list[float]``; without it, both actions fall back to ``embed_texts()``
    (right for the default OpenAI embedder, which treats query and document
    text identically).
    """

    def __init__(self, embedder: TextEmbedder) -> None:
        self._embedder = embedder

    def embed(self, text: str, memory_action: str | None = None) -> list[float]:
        if memory_action == "search":
            query_fn = getattr(self._embedder, "embed_query_text", None)
            if query_fn is not None:
                return query_fn(text)
        return self._embedder.embed_texts([text])[0]

    def embed_batch(self, texts: list[str], memory_action: str = "add") -> list[list[float]]:
        if memory_action == "search":
            query_fn = getattr(self._embedder, "embed_query_text", None)
            if query_fn is not None:
                return [query_fn(t) for t in texts]
        return self._embedder.embed_texts(list(texts))


# 同一个 memory_root 对应的 qdrant 本地/嵌入式存储只能被一个 mem0.Memory 客户端
# 连接持有——这跟 LocalMemoryStore 时代（自建 SQLite，WAL 模式原生支持多连接
# 并发读）完全不同，是真实复现过的问题：任何调用方只要在多线程/多进程里对
# 同一个 memory_root 各自 new 一个 VoiceMem（比如线程池并发跑 QA，每次调用
# 都建一个新 VoiceMem 实例），第二个连接一建立，前一个连接后续所有操作直接
# 报 "Storage folder ... is already accessed by another instance of Qdrant
# client"——不是偶发，是必现（真实复现：LoCoMo 152 题、16 个 worker 线程的
# 评测跑下来，137 题因为这个直接失败，只有 15 题侥幸抢到了锁）。
# 用 (qdrant_path 的绝对路径) 做 key 缓存已经建好的 Memory 客户端，之后任何
# 指向同一个 memory_root 的 Mem0BackendStore 构造都复用同一个连接，不再各自
# 抢锁——同一个真实存储目录只有一个真实连接，天然线程/进程内安全。
_MEM0_CLIENT_CACHE: dict[str, Any] = {}
_MEM0_CLIENT_CACHE_LOCK = threading.Lock()


#: mem0 那几个可选依赖没装时会打 warning，但它们缺了照样能跑（spaCy 只影响
#: 词形还原、fastembed 只影响 BM25 那一路）。第一次用的人看到三行红字夹着结果，
#: 会以为跑失败了。装了就没有，没装也不该吓人——按 logger 名精确压掉这两条。
def _quiet_optional_deps() -> None:
    import logging
    import os
    if os.environ.get("VOICEMEM_VERBOSE", "0") != "0":
        return
    # mem0 的可选依赖 warning（缺了照样跑）+ 每存一条就打一行的 "Updating memory
    # with data=..."；openai SDK 每次请求打一行 "HTTP Request: POST ... 200 OK"。
    # 这些都是库的 INFO 级噪音，跑一次基础用法能刷出几十行，把真正的结果埋掉。
    for name in ("mem0", "openai", "httpx", "httpcore"):
        logging.getLogger(name).setLevel(logging.WARNING)
    for name in ("mem0.utils.spacy_models", "mem0.vector_stores.qdrant", "mem0.memory.main"):
        logging.getLogger(name).setLevel(logging.ERROR)


#: qdrant-client 的 __del__ 在解释器退出时会踩到 sys.meta_path 已清空，抛一段
#: ImportError traceback——结果早就打印完了，纯属吓人。进程退出前主动关掉，
#: 就不会走到那个坏掉的 __del__。
def _close_on_exit(mem0_instance) -> None:
    import atexit

    def _close():
        try:
            mem0_instance.vector_store.client.close()
        except Exception:
            pass

    atexit.register(_close)


class Mem0BackendStore:
    """Drop-in replacement for ``LocalMemoryStore`` backed by real ``mem0.Memory``.

    Implements the same method surface ``LeftBrainMemoryRepository`` calls on
    ``self._vector_store`` (see ``memory_repository.py``): ``search``,
    ``update_memory``, ``delete_memory``, ``add_records_with_ids``,
    ``list_ids``, ``existing_for_extractor``, ``memory_ids_with_time_expr``.
    """

    def __init__(self, embedder: TextEmbedder, *, memory_root: Path) -> None:
        self._embedder = embedder  # the real embedder used for add()/search() -- see _Mem0EmbedderAdapter below
        self._path = Path(memory_root)  # for parity with LocalMemoryStore._path (used by dev scripts)

        from voicemem.utils.common import space as _space
        # 换了 embedding 又指向同一个 space 时，在这儿就说清楚，别等 qdrant 抛
        # "shapes (n,384) and (1536,) not aligned"
        _space.check_dims(memory_root, embedder.dimensions)
        _space.describe(memory_root, dims=embedder.dimensions)
        qdrant_path = _space.vectors(memory_root)
        qdrant_path.mkdir(parents=True, exist_ok=True)
        cache_key = str(qdrant_path.resolve())

        with _MEM0_CLIENT_CACHE_LOCK:
            cached = _MEM0_CLIENT_CACHE.get(cache_key)
            if cached is not None:
                self._mem0 = cached
                return

            _quiet_optional_deps()

            from mem0 import Memory
            from mem0.configs.base import MemoryConfig
            from mem0.embeddings.configs import EmbedderConfig
            from mem0.llms.configs import LlmConfig
            from mem0.vector_stores.configs import VectorStoreConfig

            history_db = _space.db(memory_root)
            config = MemoryConfig(
                vector_store=VectorStoreConfig(provider="qdrant", config={
                    "collection_name": "voicemem",
                    "embedding_model_dims": embedder.dimensions,
                    "path": str(qdrant_path),  # local/embedded qdrant, no server -- same as mem0's own default, just isolated per memory_root instead of a shared /tmp path
                }),
                # Throwaway placeholder -- constructing an OpenAIEmbedding here
                # is cheap (no network call until an actual .embed() happens,
                # see mem0/embeddings/openai.py) and MemoryConfig requires
                # *some* valid embedder provider to build at all. The real
                # embedder gets swapped in right below; this one is never used.
                embedder=EmbedderConfig(provider="openai", config={}),
                llm=LlmConfig(provider="openai", config={"model": _resolve_chat_model()}),
                history_db_path=str(history_db),
            )
            self._mem0 = Memory(config)
            _close_on_exit(self._mem0)
            # The real hook: Memory.add()/.search() call
            # self.embedding_model.embed(text, "add"|"search") directly (see
            # _Mem0EmbedderAdapter's docstring for why this, not mem0's
            # config-driven EmbedderFactory, is the correct place to plug in
            # embedder -- whatever TextEmbedder VoiceMem was constructed
            # with, not always OpenAI's).
            self._mem0.embedding_model = _Mem0EmbedderAdapter(embedder)
            _MEM0_CLIENT_CACHE[cache_key] = self._mem0

    # ── write ────────────────────────────────────────────────────────────────

    def add_records_with_ids(
        self,
        user_id: str,
        items: Sequence[tuple[str, str, str, dict[str, Any]]],
    ) -> list[str]:
        """``items`` is ``(id, text, attributed_to, metadata)`` -- the ``id``
        component is ignored (see module docstring); returns the real ids
        mem0 generated, in the same order as ``items``.
        """
        ids: list[str] = []
        for _ignored_id, text, attributed_to, metadata in items:
            t = (text or "").strip()
            if not t:
                continue
            role = "assistant" if attributed_to == "assistant" else "user"
            result = self._mem0.add(
                messages=[{"role": role, "content": t}],
                user_id=user_id,
                infer=False,
                metadata=dict(metadata or {}),
            )
            entries = result.get("results") if isinstance(result, dict) else result
            if entries:
                ids.append(str(entries[0]["id"]))
        return ids

    def add_text(self, user_id: str, text: str, *, attributed_to: str = "user",
                 metadata: dict[str, Any] | None = None) -> str:
        ids = self.add_records_with_ids(user_id, [("", text, attributed_to, metadata or {})])
        if not ids:
            raise ValueError("text 不能为空")
        return ids[0]

    def update_memory(self, memory_id: str, new_text: str,
                       session_id: int | str | None = None,
                       observed_at: str | None = None) -> bool:
        t = new_text.strip()
        if not t:
            return False
        meta: dict[str, Any] = {}
        if session_id is not None:
            meta["session_id"] = session_id
        if observed_at is not None:
            meta["created_at"] = observed_at
        try:
            self._mem0.update(memory_id, text=t, metadata=meta or None)
            return True
        except Exception:
            return False

    def delete_memory(self, memory_id: str) -> bool:
        try:
            self._mem0.delete(memory_id)
            return True
        except Exception:
            return False

    def archive_memory(self, memory_id: str) -> bool:
        """归档：把 expiration_date 设成昨天，mem0 自己的 search()/get_all()
        已经会按这个字段自动隐藏过期记忆（真实读过 mem0.memory.main.py 的
        _payload_is_expired，不是假设）——直接复用这个真实存在的机制，
        不用在 voicemem 自己的图层另外造一套"archived"标记位。
        """
        from datetime import date, timedelta
        yesterday = (date.today() - timedelta(days=1)).isoformat()
        try:
            self._mem0.update(memory_id, expiration_date=yesterday)
            return True
        except Exception:
            return False

    def unarchive_memory(self, memory_id: str) -> bool:
        """撤销归档：expiration_date 清空（mem0 update() 的 expiration_date=None
        就是清空，见其文档字符串）。"""
        try:
            self._mem0.update(memory_id, expiration_date=None)
            return True
        except Exception:
            return False

    # ── read ────────────────────────────────────────────────────────────────

    def list_ids(self, *, user_id: str) -> list[str]:
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return [str(e["id"]) for e in entries]

    def list_entries(self, *, user_id: str) -> list[dict[str, str]]:
        """全部记忆的 (id, text, date)——date 取 metadata.time_start（ingest 的 observed_at），
        没有则退回 created_at。供 schema 描述刷新等批处理用，不做向量检索。"""
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        out = []
        for e in entries:
            md = e.get("metadata") or {}
            # role 也带上：助手自己说过的话原样存在库里（见 add_text 的
            # attributed_to="assistant"），调用方要能把它们挑出来——比如 web demo
            # 的脑图只该显示"关于用户的记忆"，把助手的回复也长成节点就不对了。
            out.append({"id": str(e["id"]), "text": str(e.get("memory", "") or ""),
                        "date": str(md.get("time_start") or e.get("created_at") or "")[:10],
                        "role": str(md.get("role") or e.get("role") or "user")})
        return out

    def existing_for_extractor(self, user_id: str, *, limit: int = 50) -> list[dict[str, str]]:
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=limit)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return [{"id": str(e["id"]), "text": str(e.get("memory", ""))} for e in entries[:limit]]

    def memory_ids_with_time_expr(self, user_id: str, *, kind: str) -> set[str]:
        pat = _DURATION_RE if kind == "duration" else _DATE_RE
        result = self._mem0.get_all(filters={"user_id": user_id}, top_k=10_000)
        entries = result.get("results", []) if isinstance(result, dict) else result
        return {str(e["id"]) for e in entries if pat.search(str(e.get("memory", "") or ""))}

    def search(
        self,
        query: str,
        *,
        user_id: str,
        top_k: int = 10,
        threshold: float | None = None,
        memory_id_filter: set[str] | list[str] | None = None,
        rescue_k: int = 0,
        include_assistant: bool = False,
    ) -> list[MemorySearchHit]:
        q = query.strip()
        if not q:
            return []

        # mem0's search() has no "restrict to this explicit id set" filter --
        # only metadata filters (user_id/agent_id/run_id). When the caller
        # narrows candidates first (SearchData()'s slot/entity narrowing),
        # fetch a wide-enough candidate set from mem0 and filter client-side,
        # same as before: narrowing doesn't happen at the mem0 query itself.
        fetch_k = 10_000 if memory_id_filter else max(top_k * 3, 20)
        # search() takes user_id via filters={}, NOT a direct user_id= kwarg
        # (unlike add(), which does accept user_id= directly) -- confirmed
        # from the real installed SDK's signature, not assumed by analogy.
        # 助手说过的话也在同一个库里（role=assistant），默认不召回——问"我对什么
        # 过敏"时冒出一句"助手建议你避开坚果"，等于让它引用自己，答案会越滚越偏。
        # 只有问题本身在问"你之前说过什么"时才放进来（见 asks_about_assistant）。
        flt: dict[str, Any] = {"user_id": user_id}
        if not include_assistant:
            flt["role"] = {"ne": "assistant"}
        raw = self._mem0.search(q, filters=flt, top_k=fetch_k, threshold=0.0)
        entries = raw.get("results", []) if isinstance(raw, dict) else raw

        id_filter = set(memory_id_filter) if memory_id_filter else None
        q_words = _content_words(q)
        want_dur = bool(_DURATION_Q_RE.search(q))
        want_date = (not want_dur) and bool(_DATE_Q_RE.search(q))
        q_dates = query_dates(q)     # "下周"展开出来的那几天（见 time_expand）

        hits: list[MemorySearchHit] = []
        for e in entries:
            mid = str(e["id"])
            if id_filter is not None and mid not in id_filter:
                continue
            cos = float(e.get("score") or 0.0)
            if threshold is not None and cos < threshold:
                continue
            text = str(e.get("memory", ""))
            bonus, time_hit = _lexical_time_bonus(q_words, want_dur, want_date, text)
            bonus += date_overlap_bonus(q_dates, text)
            metadata = {k: v for k, v in e.items()
                        if k not in ("id", "memory", "score", "hash", "user_id", "created_at", "updated_at")}
            # 事件时间：Ingest 的 observed_at 同时写进了 metadata.time_start 和顶层
            # created_at，两处都取一下。这里以前什么都没取——created_at 被上面那行
            # 排除掉，time_start 又嵌在 metadata 里没摊平，于是时间一路存到了库里
            # 却从没到过 prompt，时序类问题全靠事实正文里碰巧出现的日期。
            inner = e.get("metadata") or {}
            observed = str(inner.get("time_start") or e.get("created_at") or "")[:10]
            hits.append(MemorySearchHit(
                memory_id=mid, text=text, score=cos + bonus,
                attributed_to=str(e.get("attributed_to") or "user"),
                metadata=metadata, base_score=cos, time_boost=time_hit,
                observed_at=observed if observed[:4].isdigit() else "",
            ))

        hits.sort(key=lambda h: h.base_score, reverse=True)
        base = hits[:top_k]
        if rescue_k <= 0:
            return base
        seen = {h.memory_id for h in base}
        boosted = sorted(
            (h for h in hits if h.time_boost and h.memory_id not in seen),
            key=lambda h: h.score, reverse=True,
        )
        return base + boosted[:rescue_k]
